### ISSUE TITLE
[Better Tooltips] - duplicate hex-stacking issue

### ISSUE THREAD

**Issue by RzR332Guyver** [Eradev/StolenRealmMods#2]
Seems like it stops showing how many hexes are being targeted by multiple "hazards" 
e.g: the boss that drops multiple "Runes of Exploding", the hexes won't show you if a specific hex is affected by 2 or more Runes of Exploding, making it difficult to determine how much potential damage there is.

**Comment by Eradev** [comment]
Should be fixed in 1.0.1. Please let me know if you still have the problem.

![image](https://user-images.githubusercontent.com/10186499/187016901-ed0060bd-2e3a-4765-bb41-26f23f6934f4.png)

**Comment by RzR332Guyver** [comment]
Looks like it's working properly now. Cheers.
