### ISSUE TITLE
Debug mod requires unknown password

### ISSUE THREAD

**Issue by Recoson** [Eradev/StolenRealmMods#3]
after about 2 hours of use and then a restart the debug menu required a password that I can't seem to find anywhere.

**Comment by Recoson** [comment]
![stolen](https://user-images.githubusercontent.com/118254765/201866898-fd70f292-2e47-4ac1-894f-19c458033343.png)

**Comment by Eradev** [comment]
Mine still works in 0.20.4 with the "/debug" command.

**Comment by Eradev** [comment]
![image](https://user-images.githubusercontent.com/10186499/202877000-88b791aa-e6fe-420a-bed9-527b9f626802.png)

**Comment by Eradev** [comment]
Confirmed on Discord to be still working. Closed.
