### ISSUE TITLE
[Better Tooltips] - Can't click/move on ground with elements

### ISSUE THREAD

**Issue by RzR332Guyver** [Eradev/StolenRealmMods#5]
Whenever an element is cast on the ground I can not move to it, let alone cast any self-spells if standing on the hex. Almost as if the hex itself is "invalid"
![image_2022-11-20_154341512](https://user-images.githubusercontent.com/1342961/202932984-7f637248-780a-4254-87b2-2c5daf369deb.png)
Also getting a ton of red-errors in the console

Edit* Seems like some enemies can't be targeted either when standing in patches.

**Comment by Eradev** [comment]
I need more details on how to reproduce it. Thanks.

**Comment by Eradev** [comment]
This only happens in MP as clients don't have access to a certain list.

**Comment by Eradev** [comment]
The plugin crash should be fixed in 1.0.3.

Re-open the issue if it hasn't been fixed.
