### ISSUE TITLE
Hello I have a question.

### ISSUE THREAD

**Issue by syliber** [Eradev/StolenRealmMods#6]
The mod description is so simple that I'm not sure how to install it. It would be easier to install the mod if there is a description of the mod through pictures or videos.

**Comment by Eradev** [comment]
There's a page called "Dependencies & Instructions" on every mod. It's the same for every Unity game.

![image](https://user-images.githubusercontent.com/10186499/221387714-e7e5d174-e08f-4c94-b378-d4126eaea95a.png)
