### ISSUE TITLE
questions sur mods 

### ISSUE THREAD

**Issue by liang77** [Eradev/StolenRealmMods#7]
Bonjour, je suis désolé de vous envoyer un message de cette manière, car votre compte steam n'a pas activé la fonction message, et je n'ai pas trouvé votre email.

J'ai récemment utilisé votre mod pour Stolen Realm, puis j'ai soudainement réalisé que j'avais également utilisé votre mod pour Monster Sanctuary auparavant. Merci beaucoup pour vos mods, ils ont grandement amélioré mon expérience de jeu.

Je vois sur votre git que vous avez créé plus de mods pour Stolen Realm, mais que vous n'avez pas publié tous les mods sur WorkShop. Puis-je vous demander si vous publierez UnlockFortunes et StatPoints à l'avenir ? Je suis très intéressé par ces deux mods.

Je suis un débutant en français et j'espère que la déclaration ci-dessus capture exactement ce que je veux dire.

**Comment by Eradev** [comment]
Merci beaucoup! Ça me fait plaisir d'entendre que vous avez apprécié les mods que j'ai créés.

* Je peux publier StatPoints.
* Pour ce qui est de UnlockFortunes, il y a une option dans le menu de débug qui fait sensiblement la même chose. Je ne pense pas que ça vaut la peine de le publier.

Bon jeu!

**Comment by Eradev** [comment]
https://modworkshop.net/mod/41681
