### ISSUE TITLE
Skill Points Mod error

### ISSUE THREAD

**Issue by alu0100463118** [Eradev/StolenRealmMods#8]
Hi, im having trouble with this mod. Depending on the BepInEx version this mod doesn't load, or when it loads the skill page of the game looks like this:

![1](https://github.com/Eradev/StolenRealmMods/assets/14906924/0a7052c9-a389-43fb-b39b-1da9d5c1ceb5)
![2](https://github.com/Eradev/StolenRealmMods/assets/14906924/b3b4a438-3e33-4ea4-838b-a9dcbb128318)

The LogOutput file say this:

[Info   :   BepInEx] Running under Unity v2020.3.48.12060081
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Command Handler 1.2.1]
[Info   :Command Handler] Command key set to '/'
[Info   :Command Handler] Plugin eradev.stolenrealm.CommandHandler is loaded!
[Info   :   BepInEx] Loading [Skill Points 1.0.1]
[Warning:  HarmonyX] AccessTools.DeclaredProperty: Could not find property for type SkillRefundManager and name SelectedRefundCharacter
[Message:   BepInEx] Chainloader startup complete

I'm on version 0.22.3 of stolen realm.

Thank you.

**Comment by Eradev** [comment]
Should be fixed in 1.1.0
