### ISSUE TITLE
skills per level and command handler not working for 1.1.14

### ISSUE THREAD

**Issue by pherixu** [Eradev/StolenRealmMods#9]
title

**Comment by Eradev** [comment]
Post your error log. Still working on my side.

**Comment by pherixu** [comment]
[Message:   BepInEx] BepInEx 5.4.23.2 - Stolen Realm (12/1/2024 5:39:07 PM)
[Info   :   BepInEx] Running under Unity v2022.3.10.16725906
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [Command Handler 1.3.0]
[Info   :Command Handler] Command key set to '/'
[Info   :Command Handler] Plugin eradev.stolenrealm.CommandHandler is loaded!
[Info   :   BepInEx] Loading [Skill Points 1.2.0]
[Info   :Skill Points] Plugin eradev.stolenrealm.SkillPoints is loaded!
[Info   :   BepInEx] Loading [Stat Points 1.1.0]
[Info   :Stat Points] Plugin eradev.stolenrealm.StatPoints is loaded!
[Message:   BepInEx] Chainloader startup complete


this is the logoutput from stolenrealm/bepinex weirdly enough it shows the mods are loading in fine, any idea why the command line doesn't show up when hitting /?
